classDiagram
    class Game{
        +pygame.Surface game_surface
        +Block current_block
        +ScoreBoard score_board
        +bool game_over
        +bool paused
        +__init__(self)
        +run(self)
        +pause(self)
        +resume(self)
        +check_game_over(self)
        +draw(self)
    }
    class Block{
        +pygame.Rect block
        +int x
        +int y
        +__init__(self, x, y)
        +move(self, x, y)
        +rotate(self)
        +draw(self, surface)
    }
    class ScoreBoard{
        +int score
        +int high_score
        +__init__(self)
        +update_score(self, score)
        +get_high_score(self)
        +reset_score(self)
        +draw(self, surface)
    }
    Game "1" -- "1" Block: has
    Game "1" -- "1" ScoreBoard: has
