quadrantChart
    title Reach and engagement of campaigns
    x-axis Low Reach --> High Reach
    y-axis Low Engagement --> High Engagement
    quadrant-1 We should expand
    quadrant-2 Need to promote
    quadrant-3 Re-evaluate
    quadrant-4 May be improved
    "Python Snake Game": [0.3, 0.4]
    "Slither.io": [0.7, 0.6]
    "Snake '97": [0.4, 0.3]
    "Snake VS Block": [0.6, 0.5]
    "Happy Snakes": [0.5, 0.4]
    "Snake Rivals": [0.7, 0.7]
    "Our Target Product": [0.6, 0.6]
